apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-test
spec:
  storageClassName: fortress-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

